### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by aitap** [aitap/cmocean#1]
As suggested by Clark Richards and  Daniel Kelley in e-mail exchange, being able to request a particular version of palettes would be nice. One possible interface is

```r
col <- switch(getOption("cmcolor-version", 1),
1=(values for version 1),
2=(values for version 2))
```

Future version of `convert.r` would need to loop over [tags in matplotlib/cmocean](/matplotlib/cmocean/releases) and collect all versions of all palettes, then make a choice based on the user input, e.g. choose `max(version[version <= user.version])`.

Or something.

**Comment by aitap** [comment]
Now that we [meet CRAN quality standards](https://cran.r-project.org/package=cmocean), there is a [branch](https://github.com/aitap/cmocean/tree/versioning) with a very simple versioning interface that adds an optional argument with desired [git tag from original repo](https://github.com/matplotlib/cmocean/releases), e.g.

```r
image(x, y, z, col = cmocean('thermal', '2.0')(100))
```

It is, of course, possible to have

```r
cmocean <- function(name, clip = 0, start = clip/2, end = 1 - clip/2) {
  cols <- palettes[[getOption("cmcolor-version", '2.0')]][[name]]
  ...
}
```
(i.e. no function parameter) instead.

@richardsc, @dankelley, any more ideas to implement and try?

**Comment by dankelley** [comment]
I'll play with it a while to see if anything comes to mind, but my first impression is that this is very well done!

BTW there are some warnings from `devtools::check()`, viz.
```R
checking for code/documentation mismatches ...
   Codoc mismatches from documentation object 'cmocean':
   cmocean
     Code: function(name, version = "2.0", clip = 0, start = clip/2, end =
                    1 - clip/2)
     Docs: function(name, clip = 0, start = clip/2, end = 1 - clip/2)
     Argument names in code not in docs:
       version
     Mismatches in argument names:
       Position: 2 Code: version Docs: clip
       Position: 3 Code: clip Docs: start
       Position: 4 Code: start Docs: end
```

**Comment by richardsc** [comment]
I like it so far, but I also like the interface of specifying the version as an option ... An good way of achieving something like the latter, with the former API would be to do something like:
```r
cmVersion <- '1.2'
...
cmocean('haline', cmVersion)
...
```
so that all colors can be updated by only changing one line of code.

The biggest disadvantage to the `options` approach is that not a lot of beginning users know about package-specific options. Partly that means it's a problem of advertising (i.e. can highlight it in the vignette), but I suspect more will encounter (and appreciate) the versioning capabilities if it is a specific argument as coded right now.

@dankelley, pretty sure the devtools error is because the `version` argument has not yet been documented (owing the two potential options).

**Comment by aitap** [comment]
We can have the best of both worlds by getting the option value in default argument value:

```r
cmocean <- function(name, version = getOption("cmcolor-version", '2.0'), ...)
```

Or would that be excessive?

**Comment by dankelley** [comment]
I am coming around to not using `getOption` at all, because
1. it makes script behaviour depending on something that is not in the script.  For this reason, I hard-wire any such values in individual scripts, if I think there is *any* chance of sharing them.
2. Quite a few users will not know how to set an option, and if they are going to be distracted by looking things up, I'd rather they go to one of Kristen's papers.

Sorry for withdrawing my suggestion!

**Comment by richardsc** [comment]
@dankelley did you see the proposal with the option as the default arg? That encompasses both situations, and is how we handle similar things in oce (like oceMgp, etc). 

I like the "best of both worlds" proposal.

**Comment by dankelley** [comment]
Yup, I saw that.  I do like it (if not, it wouldn't be used so much in oce!) although I still wonder whether users will understand it. My bigger concern is reason 1 that listed. This is why I often put
```R
options(oceEOS="gsw")
```
at the start of scripts that I show to students.

I could go either way on this, because explaining what it means in the
```R
#' @param version
```
line will be sufficient, either way.

**Comment by richardsc** [comment]
My vote is for using a `cmocean-version` option, and having the `getOption()` call as the default value for the `version=` argument as @aitap proposed above.

**Comment by aitap** [comment]
The implementation of the versioned interface has been merged into master. Is there anything you would like to change?

**Comment by dankelley** [comment]
This looks great to me.
